# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 17:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(blank=True, default='0.0.0.0', max_length=100)),
                ('device_mac', models.CharField(blank=True, default='0', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='Elektron', max_length=100)),
                ('last_state_date_on', models.DateTimeField(default=datetime.datetime(2018, 5, 29, 17, 29, 13, 83549))),
                ('last_state_date_off', models.DateTimeField(default=datetime.datetime(2018, 5, 29, 17, 29, 13, 83576))),
                ('enabled', models.BooleanField(default=False)),
                ('last_run', models.DateTimeField(default=datetime.datetime(2018, 5, 29, 17, 29, 13, 83649))),
                ('state_counter_on', models.IntegerField(default=0)),
                ('state_counter_off', models.IntegerField(default=0)),
                ('pluged', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='0', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='device',
            name='devicestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceState'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
