# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20171230_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pluged',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 19, 45, 59, 513973)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_state_date_off',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 19, 45, 59, 513906)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_state_date_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 19, 45, 59, 513880)),
        ),
    ]
