# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20171230_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 23, 9, 55, 504242)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_state_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 23, 9, 55, 504157)),
        ),
    ]
