# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20171230_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 23, 9, 58, 417029)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_state_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 30, 23, 9, 58, 416950)),
        ),
    ]
