# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_auto_20180329_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 10, 46, 8, 143915)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_state_date_off',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 10, 46, 8, 143848)),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_state_date_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 10, 46, 8, 143823)),
        ),
    ]
