# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='persisted',
            field=models.BooleanField(default=False),
        ),
    ]
