# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetimetask',
            name='date_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datetimetask',
            name='date_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
