# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170914_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datetimetask',
            old_name='date_from',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='datetimetask',
            name='date_to',
        ),
    ]
