# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_auto_20180301_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 20, 29, 48, 920657)),
        ),
    ]
