# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_auto_20180319_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 19, 1, 50, 10, 962377)),
        ),
    ]
