# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-29 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_auto_20180329_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repetitions_done',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 16, 50, 41, 873208)),
        ),
    ]
