# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_auto_20180510_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 10, 34, 42, 85123)),
        ),
    ]
