# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_device_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='tarea', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TaskFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='deafult function name', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='0', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DataTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('data_value', models.CharField(blank=True, default='0', max_length=100)),
            ],
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='DateTimeTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('date_from', models.DateTimeField(default='0')),
                ('date_to', models.DateTimeField(default='0')),
            ],
            bases=('tasks.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='taskfunction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskFunction'),
        ),
        migrations.AddField(
            model_name='task',
            name='taskstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskState'),
        ),
    ]
