# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 22, 15, 44, 26, 200584)),
        ),
    ]
