# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170910_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstate',
            name='name',
            field=models.CharField(blank=True, default='default state name', max_length=100),
        ),
    ]
