# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-25 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180522_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_run',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 22, 5, 0, 578073)),
        ),
    ]
