# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20171009_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatask',
            name='comparator',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='repeats',
            field=models.IntegerField(default=1),
        ),
    ]
