# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20171212_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimetask',
            name='set_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='set_repeats',
            field=models.IntegerField(default=1),
        ),
    ]
